name: sembast_sqflite_common_test
description: sembast sqflite common test
version: 0.5.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sembast_sqflite: '>=2.1.0 <4.0.0'
  sembast:
  sqflite_common_ffi:
  sqflite_common:
dev_dependencies:
  test:
  process_run: '>=0.10.3'
  sembast_test:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast_test
      ref: dart2_3
    version: '>=0.1.3'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.2.0'
dependency_overrides:
  sembast_sqflite:
    path: ../sembast_sqflite
