name: sembast_sqflite_common_test
description: sembast sqflite common test
version: 0.5.0
publish_to: none

environment:
  sdk: '>=2.18.0-0 <3.0.0'

dependencies:
  sembast_sqflite: '>=0.1.0 <2.0.0'

dev_dependencies:
  sqflite_common_ffi: '>=1.0.0 <3.0.0'
  test:
  process_run: '>=0.10.3'
  pedantic: '>=1.8.0'
  sembast_test:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast_test
      ref: dart2_3
    version: '>=0.1.3'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'

dependency_overrides:
  sembast_sqflite:
    path: ../sembast_sqflite